# Generated by Django 2.2.5 on 2020-08-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('audio_file', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
