# Generated by Django 2.2.5 on 2020-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0002_audioclip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
