# Generated by Django 2.2.5 on 2020-09-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0003_auto_20200831_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioclip',
            options={'ordering': ('-title',)},
        ),
    ]
