# Generated by Django 2.2.5 on 2020-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0005_auto_20200901_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tajweed2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajweed2_title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('tajweed2_audio_file', models.FileField(blank=True, default='', upload_to='')),
            ],
            options={
                'ordering': ('tajweed2_title',),
            },
        ),
    ]
