# Generated by Django 2.2.5 on 2020-09-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0009_auto_20200901_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioclip',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='audioclip',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
