# Generated by Django 2.2.5 on 2020-09-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0011_auto_20200902_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tajweed2',
            name='user',
        ),
    ]
