# Generated by Django 2.2.5 on 2020-09-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0012_remove_tajweed2_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioclip',
            options={'ordering': ['id']},
        ),
    ]
