# Generated by Django 2.2.5 on 2020-09-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutapp', '0013_auto_20200920_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancetilawah',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jazariyyah',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tajweed2',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tajweed3',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='advancetilawah',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='audioclip',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='jazariyyah',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tajweed2',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tajweed3',
            name='pub_date',
        ),
    ]
